name: calc
description:  calc app.
publish_to: none
version: 1.0.5+11

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line

  flutter_native_splash: ^2.1.0


  app_resources:
    path: ../local_dependencies/app_resources

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  flutter_advanced_drawer: ^1.3.1

flutter:
  uses-material-design: true




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mir_logo_no_title.png"

flutter_native_splash:

  color: "#ffffff"
  image: assets/mir_logo_1024_350.png
  android_12:
  android_gravity: center
  ios_content_mode: center
  fullscreen: true